"""add field definition and violation field value tables

Revision ID: bb318ccc59c1
Revises: 48165b6d57e2
Create Date: 2025-04-30 15:54:33.696045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bb318ccc59c1'
down_revision: Union[str, None] = '48165b6d57e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('users') # Commented out as users table should exist
    # op.drop_index('ix_violations_reference', table_name='violations') # Commented out: Table doesn't exist
    # op.drop_table('violations') # Commented out: Table doesn't exist
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('violations',
    # ... (rest of violations table definition) ...
    # mariadb_engine='InnoDB'
    # )
    # op.create_index('ix_violations_reference', 'violations', ['reference'], unique=True)
    # op.create_table('users',
    # ... (rest of users table definition) ...
    # mariadb_engine='InnoDB'
    # )
    # ### end Alembic commands ###
