"""add field definition and violation field value tables

Revision ID: bb318ccc59c1
Revises: 48165b6d57e2
Create Date: 2025-04-30 15:54:33.696045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bb318ccc59c1'
down_revision: Union[str, None] = '48165b6d57e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index('ix_violations_reference', table_name='violations')
    op.drop_table('violations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('violations',
    sa.Column('reference', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('extra_fields', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('resident_name', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('resident_email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('unit_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('incident_date', sa.DATE(), nullable=True),
    sa.Column('incident_time', mysql.TIME(), nullable=True),
    sa.Column('incident_place', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('infraction_details', mysql.TEXT(), nullable=True),
    sa.Column('bylaw_sections_violated', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('building', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('incident_area', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('report_to', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('concierge_shift', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('people_involved', mysql.TEXT(), nullable=True),
    sa.Column('noticed_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('people_called', mysql.TEXT(), nullable=True),
    sa.Column('subject', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('details', mysql.TEXT(), nullable=True),
    sa.Column('initial_action', mysql.TEXT(), nullable=True),
    sa.Column('resolution', mysql.TEXT(), nullable=True),
    sa.Column('photo_paths', mysql.TEXT(), nullable=True),
    sa.Column('pdf_paths', mysql.TEXT(), nullable=True),
    sa.Column('pdf_letter_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='violations_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_uca1400_ai_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_index('ix_violations_reference', 'violations', ['reference'], unique=True)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('role', mysql.VARCHAR(length=50), server_default=sa.text("'user'"), nullable=True),
    sa.Column('temp_password', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('temp_password_expiry', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_uca1400_ai_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    # ### end Alembic commands ###
